name: Build App
on: push
jobs:
  Build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
         #cd /Applications/Xcode*.app/Contents
         #find find ./ -name "*.car*"
         #echo "END"
         #cd Resources
         #ls
         cp /Applications/Xcode*.app/Contents/Resources/Assets.car Xcode.car
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: Xcode.car
          path: Xcode.car
