name: Build App
on: push
jobs:
  Build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
         cd /Applications/Xcode*.app
         ls
         echo "END"
         ls macOS
