name: Build App
on: push
jobs:
  Build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
          xcodebuild -sdk iphoneos -showsdks
          xcodebuild -sdk iphoneos14.3 download
