name: Build App
on:
  workflow_dispatch:
    inputs:
      XCProjectZip:
        description: 'XCProject Zip Base64'
        required: true
        type: string
jobs:
  Build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
            echo "${{inputs.XCProjectZip}}" base64 -d > XCProject.zip
            unzip XCProject.zip -d XCProject
            ls XCProject

