name: Build App
on: push
jobs:
  Build:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
         test = $(pwd)
         cd /Applications/Xcode*.app/Contents/Resources
         ls
         cp Assets.car "$test/Xcode.car"
      - name: Upload 
        uses: actions/upload-artifact@v3
        with:
          name: Xcode.car
          path: Xcode.car
